name: build linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.3'
    - name: qmake
      run: qmake c45b.pro 
